aurora improvements
schubergphilis/terraform-aws-mcaf-aurora pull request #18
Opened 2021-01-19 11:45 UTC by TonDraaijer

2021-01-26 18:39 UTC, marwinbaumannsbp requested changes

2021-01-26 18:39 UTC, marwinbaumannsbp commented on variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2021-01-26 18:39 UTC, marwinbaumannsbp commented on variables.tf
> +  description = "Specifies whether Performance Insights is enabled or not."
```suggestion
  description = "Specifies whether Performance Insights is enabled or not"
```

2021-01-26 18:39 UTC, marwinbaumannsbp commented on variables.tf
> +  description = "The ARN of the policy that is used to set the permissions boundary for the role."
```suggestion
  description = "The ARN of the policy that is used to set the permissions boundary for the role"
```

2021-01-26 18:39 UTC, marwinbaumannsbp commented on variables.tf
> +variable "performance_insights_kms_key_id" {
We can remove this variable and reuse `kms_key_id`

2021-01-28 13:31 UTC, marwinbaumannsbp submitted a review, later dismissed

2021-01-28 13:32 UTC, svanharmelen requested changes
As for the variables, please keep a consistent ordering (type, default, description)... Will have a closer look at the rest later today.

2021-01-28 13:34 UTC, banovicn commented
let me rearrange (sort by name) all the variables and double check ordering to fulfil needed format

2021-01-28 15:21 UTC, svanharmelen commented
Just FYI for anyone following this PR... We discussed it and it should be fine now. But before we merge it @banovicn will ask to test the updated code one more. If all is good, we can merge the PR and tag a new release.

2021-02-12 07:41 UTC, marwinbaumannsbp commented
> Just FYI for anyone following this PR... We discussed it and it should be fine now. But before we merge it @banovicn will ask to test the updated code one more. If all is good, we can merge the PR and tag a new release.

@svanharmelen the module has been tested successfully, can you merge and tag a new release?

2021-02-12 07:58 UTC, svanharmelen approved these changes

2021-02-12 07:58 UTC, merged

2021-02-12 07:59 UTC, svanharmelen commented
Done... Released version v0.4.0.