Feature/support snapshot identifier
schubergphilis/terraform-aws-mcaf-aurora pull request #19
Opened 2021-02-22 13:53 UTC by rogiermccv

Add support to allow the use of a final snapshot to be used for importing data into a new instance. This is useful when destroying and recreating an instance during migrations of instances.

2021-02-22 13:59 UTC, shoekstra requested changes

2021-02-22 13:59 UTC, shoekstra commented on variables.tf
> +  default     = ""
Hi @rogiermccv, better to use `null` instead of an empty string here:

```suggestion
  default     = null
```

2021-02-22 13:59 UTC, shoekstra commented on variables.tf
> +  description = "DB snapshot to create this database from"
```suggestion
  description = "Database snapshot identifier to create the database from"
```

2021-02-22 14:02 UTC, rogiermccv reviewed
commited the changes! thanks!

2021-02-22 14:03 UTC, rogiermccv reviewed
commited changes

2021-02-23 11:33 UTC, marwinbaumannsbp approved these changes

2021-02-23 11:50 UTC, shoekstra approved these changes

2021-02-23 11:51 UTC, merged