add performance_insights_kms_key_id
schubergphilis/terraform-aws-mcaf-aurora pull request #20
Opened 2021-04-13 23:37 UTC by rogiermccv

without this var if kms_key_kd is set, performance insights
can't be disabled, forcing you to use an instance type that
supports PI (>=large). This increases costs

2021-04-14 06:30 UTC, svanharmelen commented
So it's not possible to set [this](https://github.com/schubergphilis/terraform-aws-mcaf-aurora/blob/master/variables.tf#L162) to `false` to disable the insights? So what happens if you set this to `false` and also set a KMS key ID?

2021-04-14 06:37 UTC, svanharmelen requested changes

2021-04-14 06:37 UTC, svanharmelen commented on variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2021-04-14 06:37 UTC, svanharmelen commented on variables.tf
> +}
If you are sure that setting `performance_insights = false` isn't possible to solve this, then I propose to remove that variable and use this one to determine of the respective field on the resource should be `true` or `false`.

2021-04-14 06:37 UTC, svanharmelen commented on variables.tf
> +}
Hmm... Thinking some more about this, I would like to suggest another solution. See the comment on `main.tf`...

2021-04-14 06:37 UTC, svanharmelen commented on main.tf
> +  performance_insights_kms_key_id = var.performance_insights_kms_key_id
Why not do something like this instead:

```suggestion
  performance_insights_kms_key_id = var.performance_insights ? var.kms_key_id : null
```

And then omit the new variable you added?

2021-04-14 06:38 UTC, svanharmelen commented
I did already do a review, but the initial question about the `performance_insights` variable is still something that would need to be answered first IMO.

2021-08-09 11:24 UTC, marwinbaumannsbp commented
@rogiermccv are you still working on this pull?

2021-08-30 11:26 UTC, martijnvdp commented
@rogiermccv just noticed you had the same issue, i made a pr to fix the same only using the same kms var : https://github.com/schubergphilis/terraform-aws-mcaf-aurora/pull/23

2022-01-03 16:00 UTC, martijnvdp commented
annyone going to fix this ?

2022-01-03 19:46 UTC, svanharmelen commented
Closing this one in favor of #27

2022-01-03 19:46 UTC, closed without merging